---
title: "Heygate estate regeneration"
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 2019-11-11 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: "Heygate estate lost to regeneration"
baseurl: "/heygate-regeneration"
url: http://35percent.org
color: "#f2f2f2"
